CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS card_games (
    id VARCHAR(16) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS editions (
    id VARCHAR(16) PRIMARY KEY,
    card_game_id VARCHAR(16) NOT NULL,
    name VARCHAR(150) NOT NULL,
    CONSTRAINT fk_editions_game FOREIGN KEY (card_game_id)
        REFERENCES card_games (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cards (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name_en VARCHAR(255) NOT NULL,
    name_pt VARCHAR(255) NULL,
    edition_id VARCHAR(16) NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    rarity VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cards_edition FOREIGN KEY (edition_id)
        REFERENCES editions (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_cards_name_en CHECK (CHAR_LENGTH(TRIM(name_en)) > 0),
    CONSTRAINT chk_cards_image_path CHECK (CHAR_LENGTH(TRIM(image_path)) > 0),
    CONSTRAINT chk_cards_rarity CHECK (CHAR_LENGTH(TRIM(rarity)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
